tests/ui/async-await/issues/issue-78600.rs
==========================================

Last edited: 2023-03-30 20:35:59

Contents:

.. code-block:: rs

    // edition:2018

struct S<'a>(&'a i32);

impl<'a> S<'a> {
    async fn new(i: &'a i32) -> Result<Self, ()> {
        //~^ ERROR: `async fn`
        Ok(S(&22))
    }
}

fn main() {}


