tests/ui/async-await/issue-77993-2.rs
=====================================

Last edited: 2023-03-30 20:35:59

Contents:

.. code-block:: rs

    // edition:2018

async fn test() -> Result<(), Box<dyn std::error::Error>> {
    macro!();
    //~^ ERROR expected identifier, found `!`
    Ok(())
}

fn main() {}


