tests/ui/issues/issue-87707.rs
==============================

Last edited: 2023-03-30 20:35:59

Contents:

.. code-block:: rs

    // test for #87707
// edition:2018
// run-fail
// exec-env:RUST_BACKTRACE=0
// check-run-results
// needs-unwind uses catch_unwind

use std::sync::Once;
use std::panic;

fn main() {
    let o = Once::new();
    let _ = panic::catch_unwind(|| {
        o.call_once(|| panic!("Here Once instance is poisoned."));
    });
    o.call_once(|| {});
}


